// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovoBanco.Infraestrutura.Context;

namespace NovoBanco.Infraestrutura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211025123727_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovoBanco.Dominio.Entidades.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDoCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BANCOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "001",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 239, DateTimeKind.Local).AddTicks(9653),
                            Nome = "BANCO DO BRASIL"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "070",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5767),
                            Nome = "BRB"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "104",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5811),
                            Nome = "CAIXA ECONÔMICA FEDERAL"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "429",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5813),
                            Nome = "BANCO INTER"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Codigo = "237",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5814),
                            Nome = "BRADESCO"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Codigo = "008",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5819),
                            Nome = "SANTANDER"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Codigo = "756",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5820),
                            Nome = "SICOOB"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Codigo = "048",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5821),
                            Nome = "ITAU"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Codigo = "422",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5823),
                            Nome = "SAFRA"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Codigo = "477",
                            DataDoCadastro = new DateTime(2021, 10, 25, 9, 37, 27, 240, DateTimeKind.Local).AddTicks(5825),
                            Nome = "CITIBANK"
                        });
                });

            modelBuilder.Entity("NovoBanco.Dominio.Entidades.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("BancoId")
                        .HasColumnType("int");

                    b.Property<string>("Conta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDoCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.ToTable("CONTASBANCARIAS");
                });

            modelBuilder.Entity("NovoBanco.Dominio.Entidades.ContaBancaria", b =>
                {
                    b.HasOne("NovoBanco.Dominio.Entidades.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });
#pragma warning restore 612, 618
        }
    }
}
